// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// MpcSessionManagerClient is the client API for MpcSessionManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MpcSessionManagerClient interface {
	NewSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*SessionConfig, error)
	GetSessionConfig(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*SessionConfig, error)
	Inbox(ctx context.Context, in *VecMessage, opts ...grpc.CallOption) (*Void, error)
	Outbox(ctx context.Context, in *VecMessage, opts ...grpc.CallOption) (*VecMessage, error)
	Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PingResponse, error)
}

type mpcSessionManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewMpcSessionManagerClient(cc grpc.ClientConnInterface) MpcSessionManagerClient {
	return &mpcSessionManagerClient{cc}
}

func (c *mpcSessionManagerClient) NewSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*SessionConfig, error) {
	out := new(SessionConfig)
	err := c.cc.Invoke(ctx, "/svarog_messenger.MpcSessionManager/NewSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSessionManagerClient) GetSessionConfig(ctx context.Context, in *SessionId, opts ...grpc.CallOption) (*SessionConfig, error) {
	out := new(SessionConfig)
	err := c.cc.Invoke(ctx, "/svarog_messenger.MpcSessionManager/GetSessionConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSessionManagerClient) Inbox(ctx context.Context, in *VecMessage, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := c.cc.Invoke(ctx, "/svarog_messenger.MpcSessionManager/Inbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSessionManagerClient) Outbox(ctx context.Context, in *VecMessage, opts ...grpc.CallOption) (*VecMessage, error) {
	out := new(VecMessage)
	err := c.cc.Invoke(ctx, "/svarog_messenger.MpcSessionManager/Outbox", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mpcSessionManagerClient) Ping(ctx context.Context, in *Void, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/svarog_messenger.MpcSessionManager/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MpcSessionManagerServer is the server API for MpcSessionManager service.
// All implementations must embed UnimplementedMpcSessionManagerServer
// for forward compatibility
type MpcSessionManagerServer interface {
	NewSession(context.Context, *SessionConfig) (*SessionConfig, error)
	GetSessionConfig(context.Context, *SessionId) (*SessionConfig, error)
	Inbox(context.Context, *VecMessage) (*Void, error)
	Outbox(context.Context, *VecMessage) (*VecMessage, error)
	Ping(context.Context, *Void) (*PingResponse, error)
	mustEmbedUnimplementedMpcSessionManagerServer()
}

// UnimplementedMpcSessionManagerServer must be embedded to have forward compatible implementations.
type UnimplementedMpcSessionManagerServer struct {
}

func (UnimplementedMpcSessionManagerServer) NewSession(context.Context, *SessionConfig) (*SessionConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewSession not implemented")
}
func (UnimplementedMpcSessionManagerServer) GetSessionConfig(context.Context, *SessionId) (*SessionConfig, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionConfig not implemented")
}
func (UnimplementedMpcSessionManagerServer) Inbox(context.Context, *VecMessage) (*Void, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Inbox not implemented")
}
func (UnimplementedMpcSessionManagerServer) Outbox(context.Context, *VecMessage) (*VecMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Outbox not implemented")
}
func (UnimplementedMpcSessionManagerServer) Ping(context.Context, *Void) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMpcSessionManagerServer) mustEmbedUnimplementedMpcSessionManagerServer() {}

// UnsafeMpcSessionManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MpcSessionManagerServer will
// result in compilation errors.
type UnsafeMpcSessionManagerServer interface {
	mustEmbedUnimplementedMpcSessionManagerServer()
}

func RegisterMpcSessionManagerServer(s *grpc.Server, srv MpcSessionManagerServer) {
	s.RegisterService(&_MpcSessionManager_serviceDesc, srv)
}

func _MpcSessionManager_NewSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSessionManagerServer).NewSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svarog_messenger.MpcSessionManager/NewSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSessionManagerServer).NewSession(ctx, req.(*SessionConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpcSessionManager_GetSessionConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSessionManagerServer).GetSessionConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svarog_messenger.MpcSessionManager/GetSessionConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSessionManagerServer).GetSessionConfig(ctx, req.(*SessionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpcSessionManager_Inbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VecMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSessionManagerServer).Inbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svarog_messenger.MpcSessionManager/Inbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSessionManagerServer).Inbox(ctx, req.(*VecMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpcSessionManager_Outbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VecMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSessionManagerServer).Outbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svarog_messenger.MpcSessionManager/Outbox",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSessionManagerServer).Outbox(ctx, req.(*VecMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MpcSessionManager_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Void)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MpcSessionManagerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/svarog_messenger.MpcSessionManager/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MpcSessionManagerServer).Ping(ctx, req.(*Void))
	}
	return interceptor(ctx, in, info, handler)
}

var _MpcSessionManager_serviceDesc = grpc.ServiceDesc{
	ServiceName: "svarog_messenger.MpcSessionManager",
	HandlerType: (*MpcSessionManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewSession",
			Handler:    _MpcSessionManager_NewSession_Handler,
		},
		{
			MethodName: "GetSessionConfig",
			Handler:    _MpcSessionManager_GetSessionConfig_Handler,
		},
		{
			MethodName: "Inbox",
			Handler:    _MpcSessionManager_Inbox_Handler,
		},
		{
			MethodName: "Outbox",
			Handler:    _MpcSessionManager_Outbox_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MpcSessionManager_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svarog.proto",
}
